### ISSUE TITLE
OpenGL driver version lists Nvidia for AMD iGPU

### ISSUE THREAD

**Issue by Blisto91** [Umio-Yasuno/amdgpu_top#101]
Hi there.
Noticed something i thought i might as well report in case it wasn't known.

In my system i currently have a AMD 7950x iGPU and a Nvidia RTX 4080 dGPU and therefor have both the Nvidia proprietary and mesa drivers installed. I noticed that iGPU list the Nvidia driver at `OpenGL Driver Version`.
Note that it is the Nvidia GPU that is driving my display.
![image](https://github.com/user-attachments/assets/09813456-9d30-4810-adba-9b448a726c7b)

I'm not sure what logs would be useful here, if any, but if you need some i will try to fetch them.

**Comment by Umio-Yasuno** [comment]
Fixed in 6c0ac5a  
Thanks for your reporting.
