### ISSUE TITLE
Unsoundness in 'pub fn get'

### ISSUE THREAD

**Issue by lwz23** [Umio-Yasuno/amdgpu_top#104]
I think there is an unsound problem in the following function https://github.com/Umio-Yasuno/amdgpu_top/blob/3c9673895194883c3f5d47dafbb43491d8d64b2a/crates/libamdgpu_top/src/stat/perf_counter.rs#L106
```
pub fn get(&self, index: usize) -> u8 {
        unsafe { *self.0.get_unchecked(index) }
    }
```
**Problem Description**
The function uses unsafe { *self.0.get_unchecked(index) } to access elements without performing bounds checking. While get_unchecked can improve performance by avoiding checks, it introduces undefined behavior (UB) if the provided index is out of bounds.

**Why This Is a Problem**
If index exceeds the length of self.0 (or is otherwise invalid), the dereference operation will lead to undefined behavior.
The function does not provide any safeguards (e.g., asserts or preconditions) to ensure index is valid before the unsafe code is executed.
If self.0 is exposed to the user or otherwise indirectly modifiable, it is possible for the caller to cause memory safety issues by passing invalid index values.

**Suggestions for Fixing the Issue**
If performance is a concern, you can keep the unsafe block but add an explicit bounds check:
```
pub fn get(&self, index: usize) -> u8 {
    assert!(index < self.0.len(), "Index out of bounds");
    unsafe { *self.0.get_unchecked(index) }
}
```

**Comment by Umio-Yasuno** [comment]
Thanks for your repoting.  
For safety reasons, the following changes have been made:  

 * replace `self.0.get_unchecked(index)` with `self[index]`
 * change `PCAcc::get` to the private method
 * add assertion of index when initializing `PerfCounter`
