### ISSUE TITLE
Would you consider creating a COPR repository for this app?

### ISSUE THREAD

**Issue by Anakin1773** [Umio-Yasuno/amdgpu_top#105]
Hello. Would you consider creating a COPR repository for this app? I ask because it would be nice to be able to update without having to remove the app every time I wish to upgrade to a new release of Fedora.

**Comment by Umio-Yasuno** [comment]
I do not intend to become a package maintainer, especially for the package system that I don't use.

**Comment by Anakin1773** [comment]
> I do not intend to become _a package maintainer_, especially for the package system that I don't use.

OK then, thank you anyways.
