### ISSUE TITLE
Make better use of horizontal space in TUI

### ISSUE THREAD

**Issue by R1chterScale** [Umio-Yasuno/amdgpu_top#107]
Currently in TUI mode, the program does not make use of additional available horizontal space, moving some fields over to a parallel column may be a good idea, example attached of the current state.
![AMDGPU_TOP_TUI](https://github.com/user-attachments/assets/2c8c632e-30cc-47ab-a4d4-cc2383b3d64a)

**Comment by Umio-Yasuno** [comment]
I am currently considering a layout like this.　　
However, dynamic layout changes are difficult.　　

![Screenshot_20241212_190742](https://github.com/user-attachments/assets/c9a41527-dc5d-48f9-911e-74bfbc61c613)
