### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by aidyw** [Umio-Yasuno/amdgpu_top#12]
Hi,
Just tried to compile your code on Ubuntu 22.04.2. Never tried a RUST/CARGO compile before, but made sure your defined dependencies are setup before compiling, however it fails as below:

I have never used, coded or compiled a rust program before, so I am at a total loss where to start. Any ideas?
All the best
Aidan

....
....
Compiling libamdgpu_top v0.1.7 (/usr/src/amdgpu_top/crates/libamdgpu_top)
error[E0432]: unresolved import `std::os::fd::IntoRawFd`
  --> crates/libamdgpu_top/src/device_path.rs:49:17
   |
49 |             use std::os::fd::IntoRawFd;
   |                 ^^^^^^^^^^^^^^^^^^^^^^ no `IntoRawFd` in `os::fd`

error[E0603]: module `fd` is private
  --> crates/libamdgpu_top/src/device_path.rs:49:26
   |
49 |             use std::os::fd::IntoRawFd;
   |                          ^^ private module
   |
note: the module `fd` is defined here

error[E0599]: no method named `into_raw_fd` found for struct `File` in the current scope
  --> crates/libamdgpu_top/src/device_path.rs:55:34
   |
55 |             DeviceHandle::init(f.into_raw_fd()).map_err(|v| anyhow!(v))
   |                                  ^^^^^^^^^^^ method not found in `File`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use std::os::unix::io::IntoRawFd;
   |

Some errors have detailed explanations: E0432, E0599, E0603.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `libamdgpu_top` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `amdgpu_top v0.1.7 (/usr/src/amdgpu_top)`, intermediate artifacts can be found at `/usr/src/amdgpu_top/target`

**Comment by Umio-Yasuno** [comment]
`std::os::fd` has been public since Rust v1.66.0.

Could you try this branch?
https://doc.rust-lang.org/stable/std/os/fd/index.html

**Comment by aidyw** [comment]
Same problem:

Compiling libamdgpu_top v0.1.7 (/usr/src/amdgpu_top/crates/libamdgpu_top)
error[E0432]: unresolved import `std::os::fd::IntoRawFd`
  --> crates/libamdgpu_top/src/device_path.rs:49:17
   |
49 |             use std::os::fd::IntoRawFd;
   |                 ^^^^^^^^^^^^^^^^^^^^^^ no `IntoRawFd` in `os::fd`

**Comment by aidyw** [comment]
rustc 1.65.0

Package support on Ubuntu 22.04.2 LTS. (Ubuntu's latest LTS). Oh dear....lagging, but this will make it troublesome so many people if this is the problem. Just a heads up.

**Comment by Umio-Yasuno** [comment]
It looks like the branch is still in main or has not been updated.

> Same problem:
> 
> Compiling libamdgpu_top v0.1.7 (/usr/src/amdgpu_top/crates/libamdgpu_top) error[E0432]: unresolved import `std::os::fd::IntoRawFd` --> crates/libamdgpu_top/src/device_path.rs:49:17 | 49 | use std::os::fd::IntoRawFd; | ^^^^^^^^^^^^^^^^^^^^^^ no `IntoRawFd` in `os::fd`

**Comment by Umio-Yasuno** [comment]
I have been able to reproduce and fix the problem in my environment, so I am closing this issue.
