### ISSUE TITLE
Per process GTT and combined VRAM/GTT value

### ISSUE THREAD

**Issue by Blisto91** [Umio-Yasuno/amdgpu_top#16]
Hi there. Very cool tool :slightly_smiling_face: 

Is it planned to be able to (if possibly i don't know the technicals) show GTT per process similar to regular vram? And maybe also the ability to show both as a combined value.
This could maybe be useful on systems with shared memory where only a small portion is reported as dedicated VRAM e.g. Steam Deck.

<details>
  <summary>Screenshot from deck</summary>
  
![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/47954800/4e83d282-663c-4852-9edb-693623a86e5b)
</details>

**Comment by Umio-Yasuno** [comment]
I have already added that and it will be included in the next release.

https://github.com/Umio-Yasuno/amdgpu_top/commit/ffeaccd254572909bdc7524f31ca8cd413a6a420

![smi](https://github.com/Umio-Yasuno/amdgpu_top/assets/53935716/d9a1e6fd-cbdb-47b9-a621-bdd46ffe8e99)
![tui_000](https://github.com/Umio-Yasuno/amdgpu_top/assets/53935716/849fe3eb-7929-4679-bfed-b65a2a9c8c4f)

**Comment by Blisto91** [comment]
Nice great! Missed that commit during search, still getting used to the new github UI hehe.
