### ISSUE TITLE
undefined reference to `amdgpu_device_get_fd'

### ISSUE THREAD

**Issue by CabbageSong** [Umio-Yasuno/amdgpu_top#17]
When building with `cargo install --locked --path .`, an error launched with

>  undefined reference to `amdgpu_device_get_fd'

I saw amdgpu_device_get_fd was push to drm 18 months ago, but still not found in my local OS.

ps. I'm running 20.04.6, kernel version 5.15.0-72-generic

**Comment by Umio-Yasuno** [comment]
Could you try this branch?
https://github.com/Umio-Yasuno/amdgpu_top/tree/fd

**Comment by CabbageSong** [comment]
> Could you try this branch? https://github.com/Umio-Yasuno/amdgpu_top/tree/fd

Hi @Umio-Yasuno , thanks for your reply. It does work for me!

libdrm-2.4.107 is the latest package for ubuntu 20.04. I guess that's the reason why 'amdgpu_device_get_fd' is lost.

**Comment by CabbageSong** [comment]
BTW, I'm not sure if it is still the issue of ubuntu version. The data under fdinfo is 0 for all:
<img width="486" alt="image" src="https://github.com/Umio-Yasuno/amdgpu_top/assets/38155817/01383af1-a08e-48cb-b0d3-5d2778c7d9f1">

In addition, I found that headers are different in fdinfo:
```
~/amdgpu_top$ cat /proc/4728/fdinfo/7
pos:    0
flags:  02100002
mnt_id: 26
ino:    623
pdev:   0000:04:00.0
pasid:  32774
vram mem:       17196 kB
gtt mem:        6144 kB
cpu mem:        0 kB
gfx0:   70.59%
```
It seems that data is behind `vram mem`  and the parser is searching with `drm-memory`

**Comment by Umio-Yasuno** [comment]
The AMDGPU driver has changed the format of fdinfo to fix the calculation of engine usage.
It now uses the format along "drm-usage-stat.rst".
However, in Linux Kernel 5.15.xxx, the old format is still used.
I am not going to support the old format.

https://lists.freedesktop.org/archives/amd-gfx/2022-May/079291.html
https://docs.kernel.org/gpu/drm-usage-stats.html

**Comment by CabbageSong** [comment]
Okay. I'll try to install Ubuntu22.
