### ISSUE TITLE
PCIe Bandwidth measurement.

### ISSUE THREAD

**Issue by JoneKone** [Umio-Yasuno/amdgpu_top#26]
So I noticed when I was playing a video on youtube, the pci sent measurement increased steadily up to 1440p (around 200MB/s) and then reset to almost zero at 4k resolution

![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/1114115/b9f316cd-0dd0-487d-a33d-30159a69de3e)

Second image, I swap from 1440p youtube to 4k 
![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/1114115/68987231-5a27-4430-ba95-e0a9d1fe1695)

**Comment by Umio-Yasuno** [comment]
I have reproduced the issue.
However, in the case of MS Edge, PCIe bandwidth usage did not increase at any resolution, which I think is due to Firefox's video playback specifications.

**Comment by JoneKone** [comment]
Yes, I have had similar issues with (memory usage) when mesa has been updated. I feel it is related. The AMD card informs that 4 gigabytes of memory used then suddenly goes to zero... Something rolls over.

(This memory register roll over has been observed by my friend on windows 7) It didn't report over 4 gigabytes of memory usage, properly.

So I don't know if I'm making any sense here, as it was a bug report not a question. The value is wrong. PCI send cannotbe 1MiB/s when watching 4k video.. on my second image 215MiB/s was a value reported when I was playing it on 1440p resolution 120MiB/s when playing 1080p resolution. And 1MiB/s when playing 4k video.

**Comment by Umio-Yasuno** [comment]
If the PCIe Bandwidth Usage reported by `amdgpu_top` differ significantly from those reported by `nvtop` or `rocm-smi`, it is a bug in `amdgpu_top`.

**Comment by Umio-Yasuno** [comment]
PCIe Bandwidth Usage scales when multiple Youtube windows are open in Firefox.
So I don't think that AMDGPU's PCIe counter is causing rollover or overflow.
