### ISSUE TITLE
configuring GPU

### ISSUE THREAD

**Issue by jacekpoz** [Umio-Yasuno/amdgpu_top#28]
have you thought about adding some way to configure the GPU inside of amdgpu_top? not sure how hard it would be in the TUI, but should be doable in the GUI

I'd be happy to lend a hand :-)

**Comment by Umio-Yasuno** [comment]
Do you mean overclocking/undervolting?
I have no intention of adding such features to `amdgpu_top`.
After all, it's a monitoring tool, and there are other great tools for overclocking/undervolting.

https://gitlab.com/corectrl/corectrl
https://github.com/ilya-zlobintsev/LACT

**Comment by jacekpoz** [comment]
oh, I didn't know about LACT, thanks for that
