### ISSUE TITLE
Does not compile with `-C opt-level=3 -C target-cpu=znver3`

### ISSUE THREAD

**Issue by Teddy-Kun** [Umio-Yasuno/amdgpu_top#32]
As the title says, if you set the `RUSTFLAGS` environment variable to `-C opt-level=3 -C target-cpu=znver3` (or native when on a 3rd gen Ryzen cpu). Removing either argument will let it compile.

Note: I am on version 1.70.0 of the toolchain. The nightly version will not work because `tinyvec_macros` uses the feature `proc_macro_span_shrink` which does not exist anymore.

This should probably be reported to the upstream rust compiler though, but I thought this should still be reported here.

[Error message](https://pastebin.com/zG78qtjt)

**Comment by Umio-Yasuno** [comment]
The issue had already been reported.
https://github.com/rust-lang/rust/issues/112398

I recommend that you build with the `gui` feature disabled or do not specify excessive optimization options.
