### ISSUE TITLE
Current PCIe Link Speed is not correct

### ISSUE THREAD

**Issue by nfp0** [Umio-Yasuno/amdgpu_top#33]
The current PCIe Link Speed is showing the maximum value instead of the current value.

On my system, I have a PCIe Gen 4.0 graphics card and CPU (Radeon RX 6800 and Ryzen 7 3700X), but my motherboard only supports PCIe Gen 3.0, so the graphics card is working at Gen 3.0 speeds (8.0 GT/s), as seen on `dmesg`:
```
[    0.584108] pci 0000:0b:00.0: 126.016 Gb/s available PCIe bandwidth, limited by 8.0 GT/s PCIe x16 link at 0000:00:03.1 (capable of 252.048 Gb/s with 16.0 GT/s PCIe x16 link)
```

But the value on amdgpu_top is shown as:
`PCIe Link Speed => Gen4x16 (Max. Gen4x16`

I have read on this issue [here](https://gitlab.freedesktop.org/drm/amd/-/issues/1967) that it's possible to get the current link speed by checking the card's `pp_dpm_pcie`

On my system, running `cat /sys/bus/pci/devices/0000:0d:00.0/pp_dpm_pcie` returns:
```
0: 2.5GT/s, x1 310Mhz 
1: 8.0GT/s, x16 619Mhz *
```

**Comment by Umio-Yasuno** [comment]
Maximum number of lanes of Polaris11/Polaris12 is reported as x16 in `pp_dpm_pcie` (actually x8), so I `{current,max}_link_{speed,width}`.
I will report it to [drm/amd](https://gitlab.freedesktop.org/drm/amd/-/issues) and then change to use `pp_dpm_pcie` except in some AMD GPU chips.

**Comment by Umio-Yasuno** [comment]
Could you try this branch?
https://github.com/Umio-Yasuno/amdgpu_top/tree/pp_dpm_pcie

**Comment by nfp0** [comment]
That branch works! :smiley:  It now reports Gen3x16

But the Max value is also at Gen3x16. Gen3 is the motherboard's maximum, but not the GPU's maximum. Is it your intention to report the Max value like this?

**Comment by Umio-Yasuno** [comment]
> But the Max value is also at Gen3x16. Gen3 is the motherboard's maximum, but not the GPU's maximum. Is it your intention to report the Max value like this?

Yes. I wish to show the maximum value of a dynamically changing range.  
I think the maximum PCIe speed/width supported by the GPU and motherboard should be checked with `lspci`.

**Comment by nfp0** [comment]
I understand. Then maybe the GPU's maximum PCIe capability could be shown on the "Device Info" section?
Or perhaps have a "System Max" and "GPU Max" value?

**Comment by Umio-Yasuno** [comment]
> I understand. Then maybe the GPU's maximum PCIe capability could be shown on the "Device Info" section?
> Or perhaps have a "System Max" and "GPU Max" value?

AFAIK, there is no way to get those information from sysfs.

**Comment by nfp0** [comment]
But `dmesg` reports the configured system maximum and the GPU maximum. Could you not source the information from there or another place?

**Comment by Umio-Yasuno** [comment]
It requires implementing the same as the Linux Kernel or creating a new bindings crate.

In my opinion, users should use `lspci` to get those information.
Anyway, I am not going to implement them in `amdgpu_top`.

**Comment by nfp0** [comment]
Ok, that's understandable.
Anyway, this issue has been fixed and we can now see the current PCIe link speed, so I'm closing it.

Thank you for the fix and for this awesome program! :smile:

**Comment by Umio-Yasuno** [comment]
I found that I could get the max link on the system side from `/sys/bus/pci/devices/<pci_bus_number>/../` !  
But I don't know if it works on all platforms and AMD GPUs.

https://github.com/Umio-Yasuno/amdgpu_top/commit/6c93ce3b2a374b605fb25d59223d5ed253be8f84

```
PCIe Link Speed     : Gen3x8  (Max)
PCIe Link Speed     : Gen3x16 (System, Max)
```
