### ISSUE TITLE
PCIe Bandwidth Usage always reports zero

### ISSUE THREAD

**Issue by nfp0** [Umio-Yasuno/amdgpu_top#34]
The PCIe Bandwidth Usage indicator always reports zero, even when under heavy GPU load.

My system is as follows:
CPU: Ryzen 7 3700X
GPU: Radeon RX 6800
Motherboard: Gigabyte B450 AORUS PRO

If any more information is needed, I'll be glad to help!

**Comment by Umio-Yasuno** [comment]
Could you attach the results of `cat pcie_bw`?
`pcie_bw` is output to AMDGPU sysfs.

**Comment by Umio-Yasuno** [comment]
Could you try this branch?
https://github.com/Umio-Yasuno/amdgpu_top/tree/pp_dpm_pcie

**Comment by nfp0** [comment]
Not sure if this is what you wanted, but executing `sudo cat /sys/class/drm/card0/device/pcie_bw` outputs:

`cat: /sys/class/drm/card0/device/pcie_bw: No data available`

**Comment by Umio-Yasuno** [comment]
Ok, RDNA 1/2 GPU dose not support `pcie_bw`.

https://lists.freedesktop.org/archives/amd-gfx/2020-May/049649.html

For APUs, `pcie_bw` is not created. But for RDNA 1/2 GPU, `pcie_bw` is created as an invalid sysfs file.  

The `pcie_bw` check process needs to be improved.

**Comment by nfp0** [comment]
Oh I see.
So there is no way to check PCIe bandwidth usage on RDNA 1/2 GPUs?

**Comment by Umio-Yasuno** [comment]
> Oh I see. So there is no way to check PCIe bandwidth usage on RDNA 1/2 GPUs?

Probably, yes.  
It seems that PCIe RX/TX performance counters have been removed on RDNA GPUs.

**Comment by nfp0** [comment]
Got it! If I can help testing anything with my RDNA 2 card in the future, please ping me.
