### ISSUE TITLE
The device info panel cannot be made thinner or hidden

### ISSUE THREAD

**Issue by Danny3** [Umio-Yasuno/amdgpu_top#36]
Hello!

I want to be able to make the device info panel (the left one) thinner, so to reduce its width.
Or hide it completely as once that I read that info i don't need it anymore, nothing is changing there or is changing rarely and I don't need it all the time.

I noticed this problem when I wanted to see if the video hardware acceleration is working on VLC and how it's affecting the stats.

So I put VLC to play a video and snapped it to the left half of my screen and this program to the right half of my screen.

Then seen that I have only half screen available to see the stats of this program, I wanted to minimize the width of its left panel so I could see more of  it's right panel that has all the sensors and graphs, but I couldn't as the left panel seems to have a minimum width that it will not go under and also there's no way to minimize / hide the left panel completely for the cases when it's not needed.

I tested this program (v0.1.10 ) on Debian 12 + KDE Plasma 5.27.5 (on Wayland session)

Can you please make it possible to change the width of the panels to as much as we want, even that it will mean that some info in that panel will be covered / not-visible or add a button to hide / restore the left panel?

Thank you!

**Comment by Umio-Yasuno** [comment]
You can toggle the visibility of the left panel via the "Info" button in the upper left corner.

**Comment by Danny3** [comment]
Oh,

Sorry @Umio-Yasuno  for opening this issue.

You're right, I can toggle the visibility of that panel clicking on that button and it works on my system.

I think I somehow didn't realize that there are buttons and not tabs.

Maybe it would be useful to add some tooltips like "Click on this button to hide the panel" when the panel is visible and "Click this button to show the panel" when the panel is hidden.

I think I hovered over it before, but I didn't guess that it's a button and if I click on it it does what I want.

BTW, the other buttons is somewhat userless.

I can see it, i can click it and it open a drop-down menu / list which I assume it should have GPUs.

But it shows only one and that one is grayed out, as I have only one.

Not sure if this intended or not but it seems to waste clicks for nothing.

Thank you!
