### ISSUE TITLE
No icon / desktop entry for the TUI version

### ISSUE THREAD

**Issue by Danny3** [Umio-Yasuno/amdgpu_top#38]
Hello!

For the programs that i have installed I prefer to have icons too, besides their names and descriptions, so that they are more user friendly, easier / faster to recognize and I can pin them to the start menu's Favorites section, the desktop or the task bar for quick and fast access.

Unfortunately for this program, the TUI and the simple-TUI doesn't have any icon / entry in the start menu.

I understand that it's not common to create icons / desktop entries for command line interfaces, but at the moment I cannot make up my mind which one i prefer to view stats (the GUI or the TUI) and it would be really nice to be able to find both of them in the start menu and from there to be able to either pin them to the desktop or the task bar or just click to open them.

I know that htop monitor, which is a TUI too, has an icon / desktop entry in the menu and can be opened from there with a click.

While opening its icon is also visible in the task bar.

And I assume it can be used as an example on how to create a desktop entry for a programs that runs in the terminal and probably this is its desktop entry file:

https://github.com/htop-dev/htop/blob/main/htop.desktop

At the moment I can click on the Htop icon in the start menu, or on the desktop or on the task bar and open it in the terminal.

For this program I have to open the terminal, type "amdgpu_top" and click enter.

It would be nice to be able to open the TUI version of this program as simple as I can do it with Htop.

I installed this program (v0.1.10 ) on Debian 12 + KDE Plasma 5.27.5 (on Wayland session)

So, what do you think, is this a good idea, to have another entry, maybe with a text like "AMDGPU TOP (TUI)" and an icon?

For me, the icon could even be the same as long as the name have this GUI / TUI distinction.

As for the simple TUI version, I have no idea if I would want an icon / desktop entry for that too, as I don't see myself using it much, but I don't think I would mind having and entry for that too in the menu, hopefully closed to the other two.

Thank you!

**Comment by Umio-Yasuno** [comment]
Added `amdgpu_top-{smi,tui}.desktop`.  
But, I did not want to add desktop menu entries without thought, so I did not include them in the package.
I thought it would be better for users to install it themselves in `~/.local/share/applications`.

https://github.com/Umio-Yasuno/amdgpu_top/commit/6ffc41e1b522b469a4b730e6818327c92b315d64

**Comment by Danny3** [comment]
> Added `amdgpu_top-{smi,tui}.desktop`. But, I did not want to add desktop menu entries without thought, so I did not include them in the package. I thought it would be better for users to install it themselves in `~/.local/share/applications`.
> 
> [6ffc41e](https://github.com/Umio-Yasuno/amdgpu_top/commit/6ffc41e1b522b469a4b730e6818327c92b315d64)

Cool, thank you!

But to be sure I understood correctly what I should do...
I need to download them from Github and put them into that folder?
That will create shortcuts just for my user, not for all users on the system, current and future ones, right?
It doesn't look that hard, but doing it for multiple computers (desktops / laptops) and for family / friends computers might become a hassle.

Is it possible that that they can be embedded in the .deb file, but not installed by default?

Like to be installed only if the .db file was installed with some specific argument, let's say --shortcuts or -s?
 Such as:

sudo apt install --shortcuts ./amdgpu-top_0.2.3_amd64.deb
Or
sudo apt install --shortcuts ./amdgpu-top_0.2.3_amd64.deb

That way after installing / reinstalling the OS on my computer or ther computers I can skip the download files and copying them into that folder part and just remember to add an argument when I install the program.

Sorry if I ask too much!

**Comment by Umio-Yasuno** [comment]
I assume the SMI and TUI modes of `amdgpu_top` are to be run from a terminal.

**Comment by Danny3** [comment]
> I assume the SMI and TUI modes of `amdgpu_top` are to be run from a terminal.

That's ok, but some of the user, myself included, don't mind to have some graphical shortcuts, like in the start menu to open those commands in a terminal.
Like I previously mentioned, Htop is TUI and work in a terminal too, but it also has an entry in the start menu to save me from opening the terminal and writing "htop" + pressing enter.
Having it in the start menu means that I can even add it as a shortcut to the task bar or to the desktop.
Which allows us to compress the "open terminal" + "type command" + "press enter" to a single or double-click.
Anyway, it was just an idea.
Maybe it would make more sense one day if this program gets more functionality and that' needs to be splitted in more different tools or with different arguments so there are more entries and these can be grouped like in Windows in a folder.
Thanks for the great work!
