### ISSUE TITLE
fdinfo should sort by VRAM by default

### ISSUE THREAD

**Issue by baryluk** [Umio-Yasuno/amdgpu_top#4]
Cool tool. I like radentop, but that is even better.

Sorting by pid I think not only is pointless, it is kind of broken. If you sort by pid, only 6 processes are shown, which basically hides what is really going on.

![image](https://user-images.githubusercontent.com/110322/231019543-ed727e4a-3d32-4069-aa4c-ae1b82e7b65a.png)

`RDD Process` is not even a correct name. It is one of the firefox processes: `pid: 1676379 cmdline:
/usr/lib/firefox-esr/firefox-esr -contentproc -parentBuildID 20230309232621 -prefsLen 36817 -prefMapSize 219046 -appDir /usr/lib/firefox-esr/browser 1639246 true rdd`, but yes, `/proc/1676379/comm` shows "RDD Process"

Additional suggestion, instead of opening every `fdinfo` file and trying to parse it for drm info, another option is to go to fd directory and read symlinks, then only use the one that points to `/dev/dri/renderD128`

**Comment by Umio-Yasuno** [comment]
> Additional suggestion, instead of opening every `fdinfo` file and trying to parse it for drm info, another option is to go to fd directory and read symlinks, then only use the one that points to `/dev/dri/renderD128`

yeah, i'm already doing that.

```rust
    for fd_link in fd_list {
        let Ok(dir_entry) = fd_link.and_then(|fd_link| Ok(fd_link.path())) else { continue };
        let Ok(link) = fs::read_link(&dir_entry) else { continue };

        // e.g. "/dev/dri/renderD128"
        if link.starts_with(target_device) {
            let Some(fd_num) = dir_entry.file_name()
                .and_then(|name| name.to_str())
                .and_then(|name| name.parse::<i32>().ok()) else { continue };
            fds.push(fd_num);
        }
    }
```
<https://github.com/Umio-Yasuno/amdgpu_top/blob/main/src/stat/fdinfo.rs#L410-L421>

**Comment by Umio-Yasuno** [comment]
Resolves: <https://github.com/Umio-Yasuno/amdgpu_top/commit/50251d3e68c83e704b0abae9ffcbb525421ac36f>
