### ISSUE TITLE
Plans to Cut a New Release?

### ISSUE THREAD

**Issue by LaurenceWarne** [Umio-Yasuno/amdgpu_top#45]
Hi!  I see a lot of great features on master such as allowing `-d` to be combined with `-J`, and the `-s` flag for JSON mode, though these don't appear to be on the most recent version (at least installed using `cargo`)?  I was wondering if you planned to cut a new release soon?

Thanks :slightly_smiling_face:

**Comment by Umio-Yasuno** [comment]
I'm reluctant to release a new version because something tiring happened related to JSON mode.

**Comment by LaurenceWarne** [comment]
Thanks!
