### ISSUE TITLE
App Fails To Start On Wayland

### ISSUE THREAD

**Issue by frkli1965** [Umio-Yasuno/amdgpu_top#48]
Hi,

As of the weekend, AMDGPU_TOP GUI no longer starts under Wayland (Hyprland/Sway)...

I am on master/main branch for amdgpu_top, seatd, wlroots, Sway and Hyprland, wayland and wayland protocols.

rustc 1.72.0

Trace is as follows:-

interface 'wl_surface' has no event 2
warning: queue 0x7f0b34000ca0 destroyed while proxies still attached:
  zwp_primary_selection_offer_v1#4278190082 still attached
  zwp_primary_selection_offer_v1#4278190081 still attached
  wl_data_offer#4278190080 still attached
  zwp_primary_selection_device_v1#38 still attached
  zwp_primary_selection_device_manager_v1#21 still attached
  wl_data_device#37 still attached
  wl_seat#36 still attached
  wl_data_device_manager#35 still attached
  wl_registry#33 still attached
warning: queue 0x55cdd9de14d0 destroyed while proxies still attached:
  xdg_wm_base#26 still attached
  wl_output#15 still attached
  wp_fractional_scale_manager_v1#14 still attached
  xdg_activation_v1#13 still attached
  zwp_text_input_manager_v3#12 still attached
  zwp_relative_pointer_manager_v1#11 still attached
  zwp_pointer_constraints_v1#10 still attached
  zxdg_decoration_manager_v1#9 still attached
  wl_seat#8 still attached
  wp_viewporter#7 still attached
  wl_subcompositor#6 still attached
  wl_compositor#5 still attached
  wl_shm#4 still attached
  wl_registry#2 still attached

Probably due to recent commits to 'wlroots' but I could be wrong.

Kind regards,

**Comment by Umio-Yasuno** [comment]
I think that problem is fixed in `smithay-client-toolkit v0.16.1` .

https://github.com/wez/wezterm/issues/3996

However, `egui` depends on `smithay-clipboard v0.6.3 (smithay-client-toolkit v1.6.0)` .

https://github.com/emilk/egui/blob/master/crates/egui-winit/Cargo.toml#L78-L79
https://github.com/Smithay/smithay-clipboard

**Comment by frkli1965** [comment]
I've added smithay-clipboard v0.6.6 and smithay-client-toolkit v0.18.0 to the amdgpu_top build deps and it compiled OK i.e.

cargo add smithay-clipboard
cargo add smithay-client-toolkit

but received a warning about the --locked flag so the app still wouldn't work.

Then I re-built without the --locked flag and amdgpu_top gui now works!!! :-)

Many thanks for the advice, much appreciated...

All the best.

**Comment by frkli1965** [comment]
Fixed so closing...
