### ISSUE TITLE
Compute load not showing in fdinfo chart when running LuxMark v3.1

### ISSUE THREAD

**Issue by terminatorul** [Umio-Yasuno/amdgpu_top#49]
Hello

Thank you for such a great monitoring tool.

I have installed amdgpu_top from git and run LuxMark v3.1 (GPU benchmark with the default scene - Luxball) to benchmark OpenCL performance with rocm-opencl package v2.0.0-40502-sles152.164 from openSUSE Tumbleweed (20231022), Linux 6.5.8.

I was expecting the compute load on the fdinfo chart to go to 100% during the benchmark, but nothing happened. I have an AMD Radeon RX 6800 XT Midnight card.

Same with GravityMark 1.81 Vulkan/OpenGL computer shaders benchmark, but GFX load does go up to 100% in this case.

Also, is there any chance amdgpu_top could show the decoder currently in use (AVC, HEVC, VP9 ...) ?

**Comment by Umio-Yasuno** [comment]
> I have installed amdgpu_top from git and run LuxMark v3.1 (GPU benchmark with the default scene - Luxball) to benchmark OpenCL performance with rocm-opencl package v2.0.0-40502-sles152.164 from openSUSE Tumbleweed (20231022), Linux 6.5.8.
> 
> I was expecting the compute load on the fdinfo chart to go to 100% during the benchmark, but nothing happened. I have an AMD Radeon RX 6800 XT Midnight card.

Could you try `ls -l /proc/$(pidof luxmark.bin)/fd` (or `ls -l /proc/$(pidof luxmark)/fd` ?) when running `luxmark`?

> Same with GravityMark 1.81 Vulkan/OpenGL computer shaders benchmark, but GFX load does go up to 100% in this case.

I do not know what `GravityMark` is doing internally.  
But the compute usage for `vkpeak` and `gamescope` is displayed.

> Also, is there any chance amdgpu_top could show the decoder currently in use (AVC, HEVC, VP9 ...) ?

There is no way to get it I think.  
UMD/KMD does not leak file codec information to the outside world.

**Comment by Umio-Yasuno** [comment]
As far as I can tell, ROCm uses `/dev/kfd`, so no usage is recorded in fdinfo.  
I will be working on support for the `amdkfd (/sys/class/kfd/kfd/proc)`  driver.

**Comment by Umio-Yasuno** [comment]
Unfortunately, I couldn't find a way to get gpu usage per process from amdkfd.

**Comment by Umio-Yasuno** [comment]
I couldn't find a way to get gpu usage per process from amdkfd,  
so I recommend that you refer to GFX activity in GPU Metrics or performance counters (GRBM, GRBM2).
