### ISSUE TITLE
HBM temp incorect

### ISSUE THREAD

**Issue by baryluk** [Umio-Yasuno/amdgpu_top#5]
```
     │HBM Temp (C) [  655,  655,  655,  655,]                                               │ 
```

RX 6900 XT does not even have HBM.

I could git out Fury X and test it later there.

**Comment by Umio-Yasuno** [comment]
Fixes: <https://github.com/Umio-Yasuno/amdgpu_top/commit/c365c7042c1b6d41f3fce548dcfc0c2a3d6f2943>

Thanks for reporting.
