### ISSUE TITLE
v0.2.2 Not building when using `--locked`

### ISSUE THREAD

**Issue by ReillyBrogan** [Umio-Yasuno/amdgpu_top#50]
Hello greetings from Solus Linux! Trying to update the Solus package to latest today and I'm getting an error when I try to build it. Solus builds with the following two commands:
```
# Setup Phase:
cargo fetch --locked

# Build Phase:
cargo build --frozen --release \
                     --no-default-features \
                     --features "tui gui json"
```
This gives us a reproducible build as the build will always use the exact versions of dependencies as declared in the cargo.lock. It appears that the cargo.lock hasn't been updated for v0.2.2 as we're getting the following error:
```
+ cargo fetch --locked
    Updating crates.io index
    Updating git repository `https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs`
error: the lock file /home/build/YPKG/root/amdgpu_top/build/amdgpu_top-0.2.2/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

Could you please take a look at this and perhaps issue a 0.2.2.1 with the issue corrected?

Also, just a thought. When I checked out the source and did a `cargo update` against it I noticed a bunch of third-party dependencies get bumps. I'd recommend setting something up like [Renovate](https://github.com/apps/renovate) or [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates), both of which are fairly easy to setup and will help automate keeping your dependencies updated.

**Comment by ReillyBrogan** [comment]
OK, I just noticed that you applied e4341f2a8dafab691837d479e6300cb35d6a79b2 to the repo after the tag and indeed v0.2.2 does build with that patch applied. My point still stands though, typically packagers are going to want to build from the tag itself and the tag itself should be build-able. I'd recommend moving the tag to the fixed commit at this point since it's still early and I don't think this has been picked up by other packagers.

**Comment by Umio-Yasuno** [comment]
Yes, that was my mistake.  
So, I released [v0.2.2-1](https://github.com/Umio-Yasuno/amdgpu_top/releases/tag/v0.2.2-1).

**Comment by ReillyBrogan** [comment]
I see it and yes it does build. For whatever reason though it's marked as a pre-release on Github.

**Comment by Umio-Yasuno** [comment]
Sorry, I have updated the dependencies and will be releasing v0.2.3.

**Comment by Umio-Yasuno** [comment]
https://github.com/Umio-Yasuno/amdgpu_top/releases/tag/v0.2.3

**Comment by ReillyBrogan** [comment]
Builds and appears to be fine, thanks!
