### ISSUE TITLE
use relative time instead of absolute time for gui graphs

### ISSUE THREAD

**Issue by StanberyTrask** [Umio-Yasuno/amdgpu_top#52]
when running for a long time all the graphs in the gui have massive time stamps in scientific notation that blend into each other 
![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/64054459/7fd9bbf2-0a67-4634-abde-8472346ebcef)
![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/64054459/dae0135b-7b40-4703-b7ef-4e2c2a910b5c)

**Comment by Umio-Yasuno** [comment]
Thanks for your report.  
I had overlooked the changes in the update to egui v0.23.0.
