### ISSUE TITLE
[Feature Request] Support for Debian (repository)

### ISSUE THREAD

**Issue by Danny3** [Umio-Yasuno/amdgpu_top#53]
Hello!

After asking other projects to add their builds to Debian's repository:

OpenSnitch
https://github.com/evilsocket/opensnitch/issues/798

KDiskMark
https://github.com/JonMagon/KDiskMark/issues/110

I would like to ask this one too as it seems great to me and I would like to have it directly into Debian's repository for quick and easy install / reinstall and upgrade!

From what I've heard the queue for accepting new packages is quite long, so it's better to start the process sooner than later.

I understand that you don't have the resources to add support for all Linux distributions, but Debian is one of the biggest and most popular distributions out there:

Ranked 4th on DistroWatch and GamingOnLinux:

https://distrowatch.com/

https://www.gamingonlinux.com/users/statistics/#LinuxDistributionsCombined-top

And it has one of the largest repository of packages (63127 on stable and 69473 on unstable)
https://pkgs.org/

So, can you please try to put this there too?

Thank you!

------------------
BTW, I asked the **GPU-viewer** project the same thing as I would love to see both projects in Debian's repository:

https://github.com/arunsivaramanneo/GPU-Viewer/issues/74

Maybe you can help each other with this task, even though I assume you can also ask the developers of the other two for help.

**Comment by Umio-Yasuno** [comment]
Should ITP requests be sent by the application developer?

**Comment by Danny3** [comment]
> Should ITP requests be sent by the application developer?

I don't know.
But I tried to look how the other two projects did it after asking them about this.
I followed the link in this comment:
https://github.com/evilsocket/opensnitch/issues/798#issuecomment-1382183103
While the owner seems to be indeed the developer of OpenSnitch, but the requester seems to be somebody else, which after reading those message there got me to this reply:

https://github.com/evilsocket/opensnitch/issues/304#issuecomment-748457182

And the message above it which seem so be a user with nickname @lamby .

Maybe he can answer this question, if he gets a notification from here.

But for the KDiskMark, project I see that the developer himself of that project created the request as he says here:

https://github.com/JonMagon/KDiskMark/issues/110#issuecomment-1356719906

And if you look into that link (request) somebody says that it likes his idea and wants to help.
So, until now it looks to me that an application developer can send this kind of request and somebody will answer, eventually with some instructions or offer to help.

**Comment by Umio-Yasuno** [comment]
I will help package it by Debian developers, but I will not send an ITP request myself.
I already provide a [deb package](https://github.com/Umio-Yasuno/amdgpu_top/releases), also we can install amdgpu_top with `cargo install amdgpu_top`.

**Comment by Danny3** [comment]
> I will help package it by Debian developers, but I will not send an ITP request myself. I already provide a [deb package](https://github.com/Umio-Yasuno/amdgpu_top/releases), also we can install amdgpu_top with `cargo install amdgpu_top`.

That's ok, thank you!
