### ISSUE TITLE
Version v0.3.0 doesn't show GUI.

### ISSUE THREAD

**Issue by Adiker** [Umio-Yasuno/amdgpu_top#54]
When trying to launch new version with --gui, nothing happens. I guess some changes were made which resulted in GUI not working as intended.

**Comment by Umio-Yasuno** [comment]
Please attach the output of `amdgpu_top --list`.

**Comment by Umio-Yasuno** [comment]
Do you get any error messages when you run `amdgpu_top --gui`?

**Comment by SimonZhongl** [comment]
I had the same problem, no output from --gui,environment is archlinux plasma wayland

**Comment by gyordanov** [comment]
same here archlinux+plasma+wayland -  the tui works fine, gui fails without error - at least nothing after starting in the terminal

**Comment by SimonZhongl** [comment]
> I had the same problem, no output from --gui,environment is archlinux plasma wayland

May I output the log somewhere to help you?

**Comment by Umio-Yasuno** [comment]
Could you try this branch?
https://github.com/Umio-Yasuno/amdgpu_top/tree/fallback_v2

**Comment by Adiker** [comment]
> Could you try this branch? https://github.com/Umio-Yasuno/amdgpu_top/tree/fallback_v2

Yes, GUI works just fine now ! Thanks for the quick fix 😀

**Comment by Umio-Yasuno** [comment]
Thanks for your reports.  
I will release v0.3.1 within a few days.

**Comment by Umio-Yasuno** [comment]
https://github.com/Umio-Yasuno/amdgpu_top/releases/tag/v0.3.1
