### ISSUE TITLE
Feature Request: Plot of VRAM / GTT over time

### ISSUE THREAD

**Issue by WeeBull** [Umio-Yasuno/amdgpu_top#56]
When running compute processes I find myself monitoring GPU memory usage a lot, and it would be great if the GUI version could have a VRAM plot, much like the fdinfo plot. I think it would be the last set of parameters to get a plot.

**Comment by Umio-Yasuno** [comment]
https://github.com/Umio-Yasuno/amdgpu_top/commit/993585770e44ffd1e32b9cd61f979d2971a3f016

![2023-11-17-131444_1317x942_scrot](https://github.com/Umio-Yasuno/amdgpu_top/assets/53935716/e30a1cd0-ca39-44d1-8ae4-c8d2aec9ffd9)
