### ISSUE TITLE
Version 0.40 removes 'gpu_metrics_v1_3' outputs from '--dump' Option

### ISSUE THREAD

**Issue by mdhayward** [Umio-Yasuno/amdgpu_top#58]
Hi there,

In version 0.3.1-1, running "amdgpu_top --dump" outputs list of variables in gpu_metrics_v1_3 at the bottom of the dump.

Some of these provided useful information not included elsewhere in the dump, such as 'average_gfx_activity'. This information could be used in scripting etc.

In 0.4.0-1, running "amdgpu_top --dump" no longer produces this output and is therefore less useful as load information is only available when starting amdgpu_top interactively.

Thanks,
Matthew Hayward.

**Comment by Umio-Yasuno** [comment]
Try running `amdgpu_top --dump --gpu-metrics` or `amdgpu_top --gpu-metrics` instead.

**Comment by mdhayward** [comment]
Perfect thanks. If that functionality is intended to be permanent, it would be useful to have the --gpu-metrics option listed in --help. Thanks again, really appreciate your work!
