### ISSUE TITLE
Dark mode for TUI

### ISSUE THREAD

**Issue by ThatOneCalculator** [Umio-Yasuno/amdgpu_top#61]
When using a dark theme in the terminal, the forced white background doesn't look great.

![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/44733677/4f88696a-9f06-4460-b1fb-deadece5c7a4)

**Comment by Umio-Yasuno** [comment]
a4c61b687c813776ac2c18ce27cd9c28e5afa9cd

`$ amdgpu_top --dark-mode`

![2023-12-25-055847_848x1104_scrot](https://github.com/Umio-Yasuno/amdgpu_top/assets/53935716/a695a39f-a98f-4192-a33c-af979447fb1a)

**Comment by ThatOneCalculator** [comment]
Thank you!
