### ISSUE TITLE
v0.6.0 release won't start

### ISSUE THREAD

**Issue by kapertdog** [Umio-Yasuno/amdgpu_top#64]
![изображение](https://github.com/Umio-Yasuno/amdgpu_top/assets/40202917/f3723812-5349-407b-95e3-b3d7f1db650b)
```
thread 'main' panicked at crates/libamdgpu_top/src/device_path.rs:87:57:
byte index 19 is out of bounds of ``
stack backtrace:
   0:     0x55f80965ec2c - <unknown>
   1:     0x55f809358ba0 - <unknown>
   2:     0x55f80962a3c2 - <unknown>
   3:     0x55f809660aee - <unknown>
   4:     0x55f809660270 - <unknown>
   5:     0x55f809661481 - <unknown>
   6:     0x55f809660eac - <unknown>
   7:     0x55f809660e06 - <unknown>
   8:     0x55f809660df1 - <unknown>
   9:     0x55f809356dc4 - <unknown>
  10:     0x55f8093600df - <unknown>
  11:     0x55f80935ff06 - <unknown>
  12:     0x55f809511578 - <unknown>
  13:     0x55f80950fd9a - <unknown>
  14:     0x55f809334325 - <unknown>
  15:     0x55f80932e8ec - <unknown>
  16:     0x55f809273c2a - <unknown>
  17:     0x55f809265f23 - <unknown>
  18:     0x55f809266339 - <unknown>
  19:     0x7fb245fedcd0 - <unknown>
  20:     0x7fb245fedd8a - __libc_start_main
  21:     0x55f809265e51 - <unknown>
  22:                0x0 - <unknown>
```

works fine on v0.5.0
![изображение](https://github.com/Umio-Yasuno/amdgpu_top/assets/40202917/693ab610-3d27-4de2-88f7-fc2e2741e8ba)

Linux 5.4.265-1-MANJARO (x64-bit) | X11 | AMD A4-6210 | AMD Radeon R3 / AMD Radeon R5 M330 with forced AMDGPU drivers

**Comment by Umio-Yasuno** [comment]
This commit should have fixed it.

https://github.com/Umio-Yasuno/amdgpu_top/commit/2792b75fdb01c3f1404e6c4f7d73fe8a64e3700e

**Comment by kapertdog** [comment]
Yes it does! Thanks, that was blazing fast
![изображение](https://github.com/Umio-Yasuno/amdgpu_top/assets/40202917/9d0c4ed7-72d1-40f4-b3f9-11fcab3f5853)

**Comment by Umio-Yasuno** [comment]
Ok, Thanks for your repoting.  
I will be releasing v0.6.1 soon.
