### ISSUE TITLE
[Question] Is DisplayPort bandwidth monitoring possible?

### ISSUE THREAD

**Issue by parkerlreed** [Umio-Yasuno/amdgpu_top#65]
I have 3 displays running through MST over USB C (Steam Deck). Doing raw calculations this would be 24.87 Gbps before compression.

DisplayStream Compression is most definitely being used to lower this requirement. 

Are there any metrics available to see in real-time what the actual bandwidth is?

**Comment by parkerlreed** [comment]
I see this mention in the kernel docs but doesn't seems to exist on the running system

https://www.kernel.org/doc/html/v6.6/gpu/amdgpu/driver-misc.html?highlight=pcie_bw#pcie-bw

**Comment by Umio-Yasuno** [comment]
> Are there any metrics available to see in real-time what the actual bandwidth is?

AFAIK, there are no such metrics.  
I recommend opening an issue about it on [drm/amd](https://gitlab.freedesktop.org/drm/amd/-/issues).
