### ISSUE TITLE
Build Problem - AMDGPUTOP-GUI - Mismatched Types!?

### ISSUE THREAD

**Issue by frkli1965** [Umio-Yasuno/amdgpu_top#66]
Hi,

Having build issues unfortunately...

Compiling amdgpu_top_tui v0.6.1 (/Builds/Arch/.../amdgpu_top/crates/amdgpu_top_tui)
error[E0308]: mismatched types
   --> crates/amdgpu_top_tui/src/view/gpu_metrics.rs:122:14
    |
122 |             (metrics.get_average_gfx_power(), "mW"),
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Option<u16>`, found `Option<u32>`
    |
    = note: expected enum `Option<u16>`
               found enum `Option<u32>`

error[E0308]: mismatched types
   --> crates/amdgpu_top_tui/src/view/gpu_metrics.rs:226:31
    |
226 |     let v = check_metrics_val(gpu_metrics.get_average_socket_power());
    |             ----------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Option<u16>`, found `Option<u32>`
    |             |
    |             arguments to this function are incorrect
    |
    = note: expected enum `Option<u16>`
               found enum `Option<u32>`
note: function defined here
   --> /Builds/Arch/.../amdgpu_top/crates/libamdgpu_top/src/stat/gpu_metrics_util.rs:3:8
    |
3   | pub fn check_metrics_val(val: Option<u16>) -> String {
    |        ^^^^^^^^^^^^^^^^^

Any help would be greatly appreciated.

Kind regards,

**Comment by Umio-Yasuno** [comment]
Fixed in this commit.
8428ca4e47aa2399146f8695a6926d443f422907

Just wondering, have you updated Cargo.lock?

**Comment by frkli1965** [comment]
> Just wondering, have you updated Cargo.lock?

It appears not so added 'cargo update' to my build script which seems to have resolved the issue... :-)

Arghhh! So much to remember with Rust! Still, learning so many thanks yet again for helping me on my journey.

Best wishes,
