### ISSUE TITLE
No decoder/encoder usage

### ISSUE THREAD

**Issue by IvanKulagin** [Umio-Yasuno/amdgpu_top#69]
Hi, on the screenshots I can see that amdgpu_top is capable of displaying decoder and encoder usage per process, but for some reason it is not working for me. Nvtop shows only decoder usage but labels it as encoder which is also kinda weird.
![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/19168617/5f77b493-4247-4d5c-8631-82e0c3aa8b08)
![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/19168617/184b9c2d-9e39-4a0f-931c-a1ff3a2bc402)

**Comment by Umio-Yasuno** [comment]
We can't get decoder/encoder usage from VCN4. We can only get media engine usage.

The AMDGPU driver handles both decoding and encoding as jobs to the encoding engine.

https://github.com/Umio-Yasuno/amdgpu_top/issues/18#issuecomment-1556054546

**Comment by IvanKulagin** [comment]
Got it, thanks
