### ISSUE TITLE
Showing/Hiding properties in the "Connector Info" shows/hides the same property for all the other connectors

### ISSUE THREAD

**Issue by fisch2** [Umio-Yasuno/amdgpu_top#73]
![grafik](https://github.com/Umio-Yasuno/amdgpu_top/assets/13035727/36fbe689-890e-4f61-a10a-72c48fe9dea8)
When clicking to show any of the connector properties for one of the connectors, the same property will also be shown for the other connectors, even though I didn't click to show the property for them. So e.g. I click to show the EDID properties for connector 92, this same property will also now show for connector 100 and 107. This happened to me on the latest commit at the time of writing, ff20dabfee3d1e1f6a7f5ae1bedc445cb63fff9d.

**Comment by Umio-Yasuno** [comment]
Thanks for your reporting.  
Fixed in 36084786c54631a69a419195ef344164fefa493a .
