### ISSUE TITLE
Issue while building the app 

### ISSUE THREAD

**Issue by mahipeddu** [Umio-Yasuno/amdgpu_top#74]
I am new to linux , i am running Ubuntu 23.10 , i am getting this issue no matter which way i try to build the app 

  Compiling eframe v0.25.0
   Compiling amdgpu_top_gui v0.7.0
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/peddu/.nvm/versions/node/v21.7.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustcOy5JaT/symbols.o" "/tmp/cargo-install3GbpBj/release/deps/amdgpu_top-71e945ca5a68ae8f.amdgpu_top.e97128a228414c0-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-install3GbpBj/release/deps" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-4659816ae037486a.rlib" "-Wl,-Bdynamic" "-ldl" "-ldl" "-ldrm" "-ldrm_amdgpu" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-install3GbpBj/release/deps/amdgpu_top-71e945ca5a68ae8f" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-all" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -ldrm: No such file or directory
          /usr/bin/ld: cannot find -ldrm_amdgpu: No such file or directory
          collect2: error: ld returned 1 exit status
          

error: could not compile `amdgpu_top` (bin "amdgpu_top") due to previous error
error: failed to compile `amdgpu_top v0.7.0`, intermediate artifacts can be found at `/tmp/cargo-install3GbpBj`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Can someone please help me out

**Comment by Umio-Yasuno** [comment]
```
sudo apt install build-essential
```

?

**Comment by Aumnescio** [comment]
I am getting a similar error even with the dependencies installed.

**Comment by Umio-Yasuno** [comment]
Do the `amdgpu_top` binary installed from the package work?  

https://github.com/Umio-Yasuno/amdgpu_top/releases/tag/v0.7.0

**Comment by BranchManager** [comment]
On fedora I get the same error when trying to build. however it does say "Error: Unable to find a match: libdrm-amdgpu" when I try to install that package. **The binary installed form the package does work though.**

**Comment by Umio-Yasuno** [comment]
I do not know if they all have the same cause and there are no logs.
And I think this is strictly a [libdrm-amdgpu-sys-rs](https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs) issue.

**Comment by Umio-Yasuno** [comment]
Could you install `libdrm-dev` ?

**Comment by Umio-Yasuno** [comment]
Or use the latest rust installed from rustup, not rust installed from the repository.

**Comment by mahipeddu** [comment]
> Or use the latest rust installed from rustup, not rust installed from the repository.

This worked for me , thank you !
