### ISSUE TITLE
Small issue with the desktop entry in the appimage. 

### ISSUE THREAD

**Issue by Samueru-sama** [Umio-Yasuno/amdgpu_top#77]
I've noticed that the .desktop file that comes with the appimage is missing the `Terminal=true` line, without this line you can't use the desktop entry to open amdgpu_top in a terminal window with an application launcher.

**Comment by Umio-Yasuno** [comment]
That is not the issue with this repository.  
I am not distributing the appimage binary with the .desktop files.

https://github.com/ivan-hc/AM/blob/main/programs/x86_64/amdgpu_top

**Comment by Umio-Yasuno** [comment]
https://github.com/ivan-hc/AM/blob/main/programs/x86_64/amdgpu_top

**Comment by Samueru-sama** [comment]
> That is not the issue with this repository. I am not distributing the appimage binary with the .desktop files.

I'm sorry but where is amdgpu_top-x86_64.AppImage in the releases page of this repo from? I downloaded that and extracted the desktop entry to confirm that issue. 

And yes I noticed the issue because I installed amdgpu_top with AM, however the very AM script does an appimage extract from the appimage to get the desktop entry.

**Comment by Samueru-sama** [comment]
> Are the desktop entry included in the binaries on the release page? That seems strange because I haven't specified any assets to the appimage build.

The appimage has the desktop entry built in, if you run `./appimagename --appimage-extract` you will be able to see the desktop entry that ships inside of it. You also need to have it otherwise appimagetool won't let you make the appimage.

That desktop entry is often taken by appimage tools to integrate the appimage into the system.

**Comment by Umio-Yasuno** [comment]
Could you please paste the contents of the desktop file?  
It may be the file generated by cargo-appimage.  

https://github.com/StratusFearMe21/cargo-appimage/blob/485be0a4393a251b7c3b20487424209bb29f7374/src/main.rs#L240

**Comment by Samueru-sama** [comment]
> Could you please paste the contents of the desktop file? It may be the file generated by cargo-appimage.
> 
> https://github.com/StratusFearMe21/cargo-appimage/blob/485be0a4393a251b7c3b20487424209bb29f7374/src/main.rs#L240

```
~/ ./amdgpu_top-x86_64.AppImage --appimage-extract && cat ./squashfs-root/*.desktop 
[Desktop Entry]
Name=amdgpu_top
Exec=amdgpu_top
Icon=icon
Type=Application
Categories=Utility;
```

The file is named cargo-appimage.desktop, so it likely gets made with it. 

>so it is unclear whether the script of AM will work correctly.

Well at least having one work is better than nothing xd. (I think it is possible still though but I don't know how to).

**Comment by Umio-Yasuno** [comment]
* As long as `cargo-appimage` is used, `cargo-appimage.desktop` cannot be deleted.
 * I changed the appimage binary to include `amdgpu_top.desktop` and `amdgpu_top-tui.desktop`.
 * You will need to fix the script of AM to actually install them.
