### ISSUE TITLE
AMDGPU DRIVERS

### ISSUE THREAD

**Issue by StormXDeV** [Umio-Yasuno/amdgpu_top#78]
As seen on this vid (https://www.youtube.com/watch?v=Ic0qXxEbWfQ) : there is a popular amd driver error, i was looking for the files that were in the video, the link in the description actually redirects me to this (https://github.com/Umio-Yasuno/unofficial-amdgpu-firmware-repo)
so do you still have the file?

**Comment by Umio-Yasuno** [comment]
No.  
The firmwares in that repository does not solve the problem mentioned in the video.  
And DO NOT create issues that are not related to this repository.
