### ISSUE TITLE
Support for Multiple GPUs on one screen

### ISSUE THREAD

**Issue by johncadengo** [Umio-Yasuno/amdgpu_top#79]
Great project. Love the work you put into this.

I noticed that there's an option on the top left corner for "Device List [ESC]" that allows you to select another device to look at.

Just wondering if it would be possible to get a high level overview of multiple GPUs on one screen?

**Comment by Umio-Yasuno** [comment]
You can use the smi mode.  

```
$ amdgpu_top --smi
```

**Comment by johncadengo** [comment]
Great, this is just what I was looking for. Thanks!
