### ISSUE TITLE
(Log below) "error: linking with `cc` failed: exit status: 1"  

### ISSUE THREAD

**Issue by Legendrik** [Umio-Yasuno/amdgpu_top#80]
Hi, so I got this error at the very end of the compiling (399/400).
I think I have to add  a path to something, but don't really know since I'm pretty new to Linux.

Here's the log:

``

error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustcDhz3Cz/symbols.o" "/home/instinct/sdnext/amdgpu_top/target/release/deps/amdgpu_top-de0c0554dc31af14.amdgpu_top.8cc20a34735e8983-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/home/instinct/sdnext/amdgpu_top/target/release/deps" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b72da0f0b49154eb.rlib" "-Wl,-Bdynamic" "-ldl" "-ldl" "-ldrm" "-ldrm_amdgpu" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/instinct/sdnext/amdgpu_top/target/release/deps/amdgpu_top-de0c0554dc31af14" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-all" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -ldrm: No such file or directory
          /usr/bin/ld: cannot find -ldrm_amdgpu: No such file or directory
          collect2: error: ld returned 1 exit status
          

error: could not compile `amdgpu_top` (bin "amdgpu_top") due to previous error
error: failed to compile `amdgpu_top v0.8.2 (/home/instinct/sdnext/amdgpu_top)`, intermediate artifacts can be found at `/home/instinct/sdnext/amdgpu_top/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
``

**Comment by Umio-Yasuno** [comment]
Please read these.

 * https://github.com/Umio-Yasuno/amdgpu_top/issues/74#issuecomment-2009143284
 * https://github.com/Umio-Yasuno/amdgpu_top?tab=readme-ov-file#build-from-source

**Comment by Legendrik** [comment]
Thank you very much!
