### ISSUE TITLE
RPM speeds in dumped info

### ISSUE THREAD

**Issue by ChaosInfinited** [Umio-Yasuno/amdgpu_top#83]
https://github.com/Umio-Yasuno/amdgpu_top/blob/ee770d7a6982647b1a9702cd2f30c384d3ce0eee/src/dump_info.rs#L212
https://github.com/Umio-Yasuno/amdgpu_top/blob/ee770d7a6982647b1a9702cd2f30c384d3ce0eee/crates/amdgpu_top_json/src/output_json.rs#L65

Hi!
I've noticed a small inconsistency in the TUI/cli, I'm not sure if it was done on purpose or not :)
Dumping info by default, non-json way, returns only max_rpm, while dumping info as json returns only current RPM.

I can prepare a PR adding current and max rpm to both dump options if you don't mind!

**Comment by Umio-Yasuno** [comment]
Please open PR.

**Comment by ChaosInfinited** [comment]
Done, tested locally and seems to be working, I leave the rest to you! Have a nice day :)
![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/96987701/0fcc0bd0-5abc-4887-b8b9-dbeea7acdbd5)
