### ISSUE TITLE
AMDGPU_top using (stealing?) Telegram's tg: Firefox/System links

### ISSUE THREAD

**Issue by mikkovedru** [Umio-Yasuno/amdgpu_top#85]
This is a weird one. I only now noticed it, so I don't know if this is a bug, a recent addition or "things have always been like this". I read/searched documentation/issues, but could not find even a whisper about this.

I just noticed, that opening web links of the highly popular Telegram messaging app in web and clicking on "View in channel" (to open in the Desktop app, instead of the web page view) invokes AMDGPU_top.

Example link:
https://t.me/DeepStateUA/19584
![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/2521942/fdbbc6e2-67a3-4462-9880-7589268d2e83)
`tg://resolve?domain=DeepStateUA&post=19584`

And yes indeed, from Firefox settings:
![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/2521942/a343aeac-9e80-4d2c-9251-a83cc3797a67)

So I wonder if this is some kind of bug in my system? If not, then I have a lot of questions like: What is the purpose of registering this `tg:` address? What is it used for? Can't there be any other way than to take the address of the very popular messaging app ("tg" doesn't really have anything in common with "amdgpu_top")? If necessary, couldn't this be handled differently, as in asking for permission instead of overwriting the default? Etc.

**Comment by Umio-Yasuno** [comment]
At least `amdgpu_top` doesn't use the "AMDGPU monitor" string, also does not associate with "tg:".  
How did you install `amdgpu_top` ? Is it a reliable way?

And what do you mean by "stealing"?

**Comment by Umio-Yasuno** [comment]
Since no one else has reported this, I think this is a problem specific to your system.

**Comment by Umio-Yasuno** [comment]
* Can you attach the associated `.desktop` file (`Name=AMDGPU monitor`) for confirmation?
 * I don't have any mime type set for the `.desktop` file for `amdgpu_top`, and it's not named "AMDGPU monitor".
   * <https://github.com/Umio-Yasuno/amdgpu_top/blob/main/assets/amdgpu_top.desktop>
   * <https://github.com/Umio-Yasuno/amdgpu_top/blob/main/assets/amdgpu_top-tui.desktop>
   * This means that the `.desktop` file installed and associated on your system was created by someone other than me.

**Comment by Umio-Yasuno** [comment]
@mikkovedru 

This may be a maliciously modified package being distributed, so should be investigated.

**Comment by mikkovedru** [comment]
I found the  `/home/mikko/.local/share/applications/AMDGPU monitor.desktop`:
```
[Desktop Entry]
Name=AMDGPU monitor
Comment=Tool that display AMD GPU utilization
Exec=amdgpu_top --gui
Icon=video-single-display-symbolic
Terminal=false
Type=Application
MimeType=x-scheme-handler/tg;
Keywords=monitor;gpu;cpu;show;gui;efficiency;fans
Actions=quit;
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true
Comment[en_GB]=
Name[en_GB]=AMDGPU monitor
```
And there is indeed a `MimeType=x-scheme-handler/tg;` line in there.

And then I started thinking and realized that this is my fault.

I installed amdgpu and everything worked fine. But at some point I noticed that I couldn't run the program from my start menu. The program was still installed in my system, but the .desktop file was missing. So I took the .desktop file of another program (from Telegram Desktop) and modified it to fit amdgpu.

Apologies for the kerfuffle!
