### ISSUE TITLE
X11 Forwarding Unusable

### ISSUE THREAD

**Issue by 7t2** [Umio-Yasuno/amdgpu_top#86]
I really enjoy amdgpu_top, I think its GUI and TUI are awesome. However, I cannot open the GUI through X11 forwarding unfortunately.

When I use `ssh -X server` and execute `amdgpu_top --gui`, I get this error with no window at all:
`thread 'main' panicked at /home/7t2/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/xdisplay.rs:118:14:
failed to request XRandR version: UnsupportedExtension
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`

Alternatively, when I use `ssh -Y server` and execute the same, I get a frozen window that does not resize correctly and cannot be interacted with.

If it helps, I'm using openssh, i3 and arch. I hope this is an easy fix, because it would be an excellent tool for remote GPGPU on AMD.

**Comment by Umio-Yasuno** [comment]
Please try this branch.  

https://github.com/Umio-Yasuno/amdgpu_top/tree/x11

**Comment by 7t2** [comment]
Thank you for your help. I compiled and ran the x11 branch, and unfortunately I get the exact same results.

To be precise, I cloned `amdgpu_top-git 0.3.0.r1.g8a76130-1` from the AUR, set the URL to `url="https://github.com/Umio-Yasuno/amdgpu_top.git#branch=x11"`, and ran `makepkg -si`. I double checked I downloaded the correct branch, and unfortunately it's made no difference.

**Comment by Umio-Yasuno** [comment]
Does it work in other applications?

**Comment by 7t2** [comment]
Yes, I often open web browsers, file managers, and other applications the same way. Is it working on your end?

**Comment by Umio-Yasuno** [comment]
> Yes, I often open web browsers, file managers, and other applications the same way. Is it working on your end?

I am not using X11 env, using Wayland.  

This issue may be on `egui`.  
https://github.com/emilk/egui/issues/3735

May be solved this if a mode to build GUI from JSON or RON data can be implemented.  
However, `amdgpu_top` is my personal project and there is no roadmap, so implementation it will take time.

**Comment by Umio-Yasuno** [comment]
I worked on the TCP server mode (JSON) and JSON-GUI mode for a few days, but decided to give up.  
The reasons are as follows
 * It affects the existing GUI implementation.
 * Stressful in development since it is a feature I personally do not use (I do not have the GPU server) and I am not looking for sponsorship.  

I recommend using `umr`.
https://gitlab.freedesktop.org/tomstdenis/umr/

```
    $ umr --gui  tcp://machineA-IP:1234
```
