### ISSUE TITLE
How to obtain the resource usage of each process

### ISSUE THREAD

**Issue by peng-bo-27** [Umio-Yasuno/amdgpu_top#87]
I don't know much abort Rust ，I want to know how to calculate the GPU resource consumption per process

## cat /proc/2217/fdinfo/99
pos:    0
flags:  02104002
mnt_id: 24
ino:    614
pasid:  32784
drm-driver:     amdgpu
drm-pdev:       0000:08:00.0
drm-client-id:  217
drm-memory-vram:        2068 KiB
drm-memory-gtt:         8192 KiB
drm-memory-cpu:         0 KiB
drm-engine-gfx: 107322799 ns                ------->keep  growing

/sys/class/drm/card0/device/mem_info_vram_total          
mean  card 0  vram_total
/sys/class/drm/card0/device/gpu_busy_percent               
mean  card 0  average_gfx_activity
/sys/class/drm/card0/device/mem_info_gtt_total             
mean  card 0  gtt_total

Is gfx usage the gpu usage of the process, and how is it calculated ？

**Comment by Umio-Yasuno** [comment]
We can calculate usage by repeatedly reading fdinfo and noting how many `drm-engine-*` have increased during that time.  

`nvtop` is written in C, so I recommend that you refer to it.  
https://github.com/Syllo/nvtop/blob/master/src/extract_gpuinfo_amdgpu.c
