### ISSUE TITLE
PRIME Reporting

### ISSUE THREAD

**Issue by FireBurn** [Umio-Yasuno/amdgpu_top#90]
Is it possible to report powered down PRIME cards as off until something else starts using them?

cat /sys/bus/pci/devices/0000\:03\:00.0/power/runtime_status will show either active or suspended

amdgpu_top currently keeps the card active

**Comment by Umio-Yasuno** [comment]
> Is it possible to report powered down PRIME cards as off until something else starts using them?

`amdgpu_top` does not currently support it.


> amdgpu_top currently keeps the card active

If `amdgpu_top` is launched while the dGPU is active, `amdgpu_top` creates the device handle, so the dGPU remains active.  

I have an idea for an optimization for a PRIME system (APU+dGPU laptop), however I do not have such a laptop.

**Comment by FireBurn** [comment]
> > Is it possible to report powered down PRIME cards as off until something else starts using them?
> 
> `amdgpu_top` does not currently support it.
> 
> > amdgpu_top currently keeps the card active
> 
> If `amdgpu_top` is launched while the dGPU is active, `amdgpu_top` creates the device handle, so the dGPU remains active.
> 
> I have an idea for an optimization for a PRIME system (APU+dGPU laptop), however I do not have such a laptop.

If you need anything tested, just at me

**Comment by Umio-Yasuno** [comment]
`amdgpu_top` has changed to drop DeviceHandle if "amdgpu_top" is the only GPU process running.  
However, I don't know if this will turn off the dGPU.  

https://github.com/Umio-Yasuno/amdgpu_top/commit/ea2ade381baddaf6041303743f75802fac9d5ee7

I think it is necessary to check whether a display connector is connected to the dGPU.  
Also, `amdgpu_top` has not yet implemented the function to detect dGPUs that are turned off at startup.

**Comment by Umio-Yasuno** [comment]
I found that `hwmon` and `gpu_metrics` should not be accessed in order for the dGPU to transition to `D3hot`.

https://github.com/Umio-Yasuno/amdgpu_top/commit/f9362416da2b1a8ead8735b458940bf0c9a7b83a

I need to know what the `sysfs` file a dGPU in `D3cold` state outputs...

**Comment by Umio-Yasuno** [comment]
@DianaNites Will the device be visible in `/sys/bus/pci/drivers/amdgpu/` even if it is in D3cold state?  
Or do we need to scan `/sys/bus/pci/devices/`?  
Also, does it work after `pci_disable_device` has been called for the device?

**Comment by Umio-Yasuno** [comment]
`amdgpu_top` has changed to drop DeviceHandle and stop reading hwmon, gpu_metrics if "amdgpu_top" is the only GPU process running.  

I think it would be difficult to further optimize it for the hybrid system (APU+dGPU) without an actual device.

**Comment by Umio-Yasuno** [comment]
Okay, `amdgpu_top` can now start up in SMI mode without waking up a suspended device.  

https://github.com/Umio-Yasuno/amdgpu_top/commit/7d1a8302624efb8c9380712b3e79a53ac352e8af

More work and time is needed to implement this in TUI, GUI, and JSON modes.

**Comment by FireBurn** [comment]
It looks good, thanks

**Comment by Umio-Yasuno** [comment]
I added support for suspended devices to TUI and GUI modes.  

Thank you for your suggestion.
