### ISSUE TITLE
Send gpu ulilization as stdout

### ISSUE THREAD

**Issue by Letus252** [Umio-Yasuno/amdgpu_top#91]
Hey, I'm looking for a way to display GPU utilization on my status bar. Is there a way to use your program to send this data to slstatus? Thanks for making this program!

**Comment by Umio-Yasuno** [comment]
* https://github.com/Umio-Yasuno/amdgpu_top?tab=readme-ov-file#example-of-using-json-mode
 * https://github.com/Umio-Yasuno/amdgpu_top/discussions/59

**Comment by Letus252** [comment]
Thank you.
