### ISSUE TITLE
Allow launching with the info panel hidden

### ISSUE THREAD

**Issue by deathtrip** [Umio-Yasuno/amdgpu_top#94]
I suggest adding a command line switch to launch with the info panel hidden, so that the people who don't need it can hide it automatically.

**Comment by Umio-Yasuno** [comment]
Instead of adding command line options, `amdgpu_top` now remembers the previous side panel state.  

https://github.com/Umio-Yasuno/amdgpu_top/commit/01f361260f39c15c80dddb5e6e7ac79440f73bb9

**Comment by Umio-Yasuno** [comment]
Since this method doesn't require users to modify the .desktop file, so I decided not to implement that command line option.
