### ISSUE TITLE
Displaying shortcut key legend should be configurable

### ISSUE THREAD

**Issue by Strykar** [Umio-Yasuno/amdgpu_top#95]
Hi, thank you for making this, I use it to monitor the iGPU of my R9-7900 CPU,
This is what `amdgpu_top` looks like (split to use 50% of the monitor width) on a 2K 32" display:

![Screenshot from 2024-09-15 20-53-26](https://github.com/user-attachments/assets/43339e75-4378-4929-9faa-3c8a9a7107ba)

If the shortcut key legend at the bottom:
```
(g)rbmg g(r)bm2 (v)ram_usage (f)dinfo
se(n)sor (m)etrics etc.
```
.. could be hidden and not always shown, it might create enough space to view a few more processes for example.

Does the legend need to be shown all the time, can't we hide it until the user presses `?` or something to make better use of the monitor's real estate?

**Comment by Umio-Yasuno** [comment]
Since the TUI screens are scrollable, saving vertical space doesn't seem to make much sense to me.
