### ISSUE TITLE
TUI interface flickers in some terminals

### ISSUE THREAD

**Issue by popey** [Umio-Yasuno/amdgpu_top#96]
Thank you for making amdgpu_top, it's rather wonderful. I use it to remotely monitor my ThinkPad Z13 with AMD APU, over SSH.

I'm seeing a flicker when the TUI updates the screen. But it's not consistent. I am using amdgpu_top built from the tip of git, using rust nightly.

Here's a video showing the flicker happening.
In this instance, I am running amdgpu_top in an SSH session from my Mac (using Alacrity as the terminal) to my Linux laptop.

https://github.com/user-attachments/assets/d8c15ca9-784a-4edf-b549-7b95a823831e

I also see flicker in:

* GNOME Terminal on Ubuntu 24.04 directly on the machine.

I do NOT see flicker in the following terminals directly on the machine:

* Alacritty 0.13.2
* Kitty 0.32.2

**Comment by Umio-Yasuno** [comment]
I couldn't reproduce it in my environment (KDE Plasma 5.27.5 + GNOME Terminal 3.46.8).

**Comment by popey** [comment]
Ok, no worries. I can use another terminal to work around it. Feel free to close this if you like 👍
