### ISSUE TITLE
How to close `amdgpu_top --gui` in Sway?

### ISSUE THREAD

**Issue by mclang** [Umio-Yasuno/amdgpu_top#97]
Hello

I just found this wonderful software but it seems that none of these regular close/quit keybindings work when using the GUI version:
- `q`
- `ctrl+q`
- `esc`

Is something missing and if so, maybe I could help? I just need to know where these kind of keybindings should be defined...

**Comment by Umio-Yasuno** [comment]
https://www.reddit.com/r/swaywm/comments/mtguzy/how_to_close_windows_which_do_not_offer_any/

**Comment by mclang** [comment]
Okay, so I need to remember another keybinding for this when every other program I use recognizes `ctrl+q`... Not optimal, but I can live with that.

**Comment by Umio-Yasuno** [comment]
Um... I didn't comment because it wasn't clear what you wanted, but I implemented the `ctrl+q` shortcut to `amdgpu_top`.  

https://github.com/Umio-Yasuno/amdgpu_top/commit/03d7c87bd66c233cb38e99243e8bc1f1ccb33cfd

**Comment by mclang** [comment]
For me `ctrl+q` works the best thank you.
