### ISSUE TITLE
Build the binary as well in the releases for use with `cargo-binstall`

### ISSUE THREAD

**Issue by stonecharioteer** [Umio-Yasuno/amdgpu_top#99]
[`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall) makes it easy to install binaries without having to use the system packages and without having to compile from scratch. I'd be happy to file a PR if you're up for it, so that this repo can have the binaries built and uploaded with releases as well.

Steps:
- [ ] Update workflows to build binaries.
- [ ] Update release workflow to upload binary.

**Comment by Umio-Yasuno** [comment]
I haven't tried this CI yet, but I have it set up to upload `amdgpu_top` binary.  
I used ripgrep as a reference, because `cargo-binstall` documentation was confusing for me...  

https://github.com/Umio-Yasuno/amdgpu_top/commit/82d2e54b553e9475ff1180f58dc2d91f6901831b
